"""empty message

Revision ID: 98895e339fa7
Revises: 5738a50fa185
Create Date: 2022-03-16 09:46:51.082751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98895e339fa7'
down_revision = '5738a50fa185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_model', sa.Column('archive', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note_model', 'archive')
    # ### end Alembic commands ###
